services:
  haskell-katas:
    image: haskell:9.8-slim
    volumes:
      - .:/app                     # Mount the project directory
      - ./ghc-cache:/root/.ghc     # Cache GHC dependencies
      - ./cabal-cache:/root/.cabal # Cache Cabal dependencies
    working_dir: /app
    tty: true                      # Enable interactive terminal
    stdin_open: true               # Allow interactive input
    #ports:
    #  - "8080:8080"
    #network_mode: host             # Use the host network
